In [6]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import torch
import tensorflow.compat.v2 as tf
import random
import os

from tcc_utils import compute_alignment_loss as torch_compute_alignment_loss
from tcc_ref.tcc_tf.alignment import compute_alignment_loss as tf_compute_alignment_loss

In [4]:
def set_seed(seed: int = 42) -> None:
    np.random.seed(seed)
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    # When running on the CuDNN backend, two further options must be set
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    # Set a fixed value for the hash seed
    os.environ["PYTHONHASHSEED"] = str(seed)
    tf.random.set_seed(seed)
    tf.experimental.numpy.random.seed(seed)
    tf.keras.utils.set_random_seed(seed)
    # When running on the CuDNN backend, two further options must be set
    os.environ['TF_CUDNN_DETERMINISTIC'] = '1'
    os.environ['TF_DETERMINISTIC_OPS'] = '1'

    print(f"Random seed set as {seed}")

Random seed set as 42


In [53]:
set_seed(0)
emb_np = np.random.rand(16,198,256).astype(np.float32)
batch_size = 16
embs_tf = tf.convert_to_tensor(emb_np)
embs_torch = torch.from_numpy(emb_np)

Random seed set as 0


In [54]:
set_seed(42)
tf_loss = tf_compute_alignment_loss(
    embs_tf, 
    batch_size, 
    stochastic_matching=True, 
    loss_type='regression_mse_var', 
    normalize_indices=False
)

Random seed set as 42
> /home/akannan2/rewards-from-human-videos/tcc-video/tcc_ref/tcc_tf/losses.py(95)regression_loss()
     94   import ipdb; ipdb.set_trace()
---> 95   beta = tf.nn.softmax(logits)
     96   true_time = tf.reduce_sum(steps * labels, axis=1)

<tf.Tensor: shape=(20, 198), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>
<tf.Tensor: shape=(198,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0

In [56]:
set_seed(42)
torch_loss = torch_compute_alignment_loss(
    embs_torch,
    batch_size
)

Random seed set as 42
> /home/akannan2/rewards-from-human-videos/tcc-video/tcc_utils.py(81)regression_loss()
     80     import ipdb; ipdb.set_trace()
---> 81     beta = F.softmax(logits, dim=1) # softmax last dimension
     82 



In [57]:
print(tf_loss, torch_loss)

tf.Tensor(0.8779804, shape=(), dtype=float32) tensor(0.9477)
